### ISSUE TITLE
Bug: Sorting in table of  buyers & suppliers, contracts, insights , equity, & product  tabs should be introduced

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#100]
![image](https://user-images.githubusercontent.com/25945530/105963153-c0c76f80-60a8-11eb-8832-48dc4d03187b.png)

**Comment by jpmckinney** [comment]
Is this closed by https://github.com/open-contracting/covid-19-procurement-explorer-public/pull/342 ?

**Comment by jpmckinney** [comment]
I think some columns are not sorting yet, like "Value (USD)" at https://www.open-contracting.health/global-overview/contracts

**Comment by jpmckinney** [comment]
Value (USD) is sorted, through reverse sorting puts null/empty values first.
