### ISSUE TITLE
Bug: Truncation of Contract title in Equity table and contract detail page

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#103]
**Context**
- https://open-contracting.health/contracts/58053

**Step**
- Global >>Equity table apply filter with contract name "ВИРОБИ МЕДИЧНОГО ПРИЗНАЧЕННЯ: НК 024 2019 58234 - СТРІЧКА ВАТЯНА, 48125 - РУЛОН МАРЛЕВИЙ"
- Check its detail page

**Actual Result**
- Contract tile with long contract name is being shown on the list and so is in its detail

**Expected Result**
- Title is to be truncated on both contract title in equity table and contract detail page followed by "....."

![image](https://user-images.githubusercontent.com/25945530/106106096-22511200-616d-11eb-850d-56d50b3276a6.png)
![image](https://user-images.githubusercontent.com/25945530/106106250-5f1d0900-616d-11eb-8179-811275521082.png)

**Comment by AbhishekSka** [comment]
@duptitung issue still exists
![image](https://user-images.githubusercontent.com/25945530/106875358-b20f3700-66fe-11eb-8ad3-413251d428f2.png)

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved
