### ISSUE TITLE
Bug: Global/Country>>Equity table>>Filter combination not working properly

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#104]
**Context**
- https://open-contracting.health/global-overview/equity

**Step**
- Global >>Equity table apply filter
- Method, Product category, Date range

**Actual Result**
-  Data different from selected filter could be viewed

**Expected Result**
- Data with the selected filter are to be listed

![image](https://user-images.githubusercontent.com/25945530/106105844-bf5f7b00-616c-11eb-850f-34874be06c04.png)

**Comment by duptitung** [comment]
@AbhishekSka  seems to be working now.

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved
