### ISSUE TITLE
Bug: Buyer profile>>Total spending>>Difference in stats of total spending in Staging and production

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#105]
![Screenshot from 2021-01-29 10-16-53](https://user-images.githubusercontent.com/25945530/106232088-423f0f00-621b-11eb-9cbf-e3a7c5d4533a.png)

**Comment by KushalRaj** [comment]
This is due to fact that in Data tab we calculate Total Spending based on all contracts. However in Buyers tab we calculate Total Spending based on buyer's contracts. Here, contracts with no buyers info are avoided.
