### ISSUE TITLE
Bug: Data>>Issue on the Visualizations

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#107]
**Context**
- https://covid19.development.opencontracting.uk0.bigv.io/global-overview/data

**Step**
Case 1:
- Global >>Data>>Contract status

Case 2:
- Country>Switch the language>>Contract status/PRODUCT DISTRIBUTION/TOP SUPPLIERS/TOP BUYERS

Case 3:
- Global/country>>Equity indicator>>When there are unassigned only have Currency code

**Actual Result**
- Case 1:  Currency unit is of 12px
- Case 2: on switching current its shows "$1.2B KES"
- Case 3: No value just only currency code on Equity indicator

**Expected Result**
- Case 1:  Currency unit is of 16px
- Case 2: on switching current its shows "1.2B KES"
- Case 3: Some message  is to be displayed

![image](https://user-images.githubusercontent.com/25945530/106738829-875ea900-6640-11eb-9417-672b9960fce7.png)
![image](https://user-images.githubusercontent.com/25945530/106740432-7dd64080-6642-11eb-9794-df37b1c81f47.png)
![image](https://user-images.githubusercontent.com/25945530/106740304-51babf80-6642-11eb-8a3a-6be261a034b2.png)

**Comment by nirazanbasnet** [comment]
Done !!
