### ISSUE TITLE
Bug: Buyer Profile/ Supplier Profile>> Change country

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#108]
Context

- https://open-contracting.health/country/mexico/buyers

Steps

- Data>>Buyer profile/ Supplier Profile>>Change country

Actual result

- The data listed on the table show no changes according to the selected country.

Expected result

- The data listed on the table should change according to the selected country.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/107326526-aabba500-6ad3-11eb-8869-d962c58cad62.png)
![image](https://user-images.githubusercontent.com/45354665/107326553-ba3aee00-6ad3-11eb-9fd9-e45664cb8b62.png)

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved @suhanapradhan
