### ISSUE TITLE
Bug: Race chart doesn't play and pause instantly.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#109]
Context

- https://open-contracting.health

Steps

- Homepage>>Map race chart

Case I
Actual result
- The chart is paused and played after few seconds of clicking the pause and play button.

Expected result
- The chart should pause and play immediately after the play pause button is clicked.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/107474655-d6ee2900-6b9a-11eb-8fe0-d956afdc34a8.png)

Case II
Actual result
- After full completion of the chart, it restarts again from the beginning.

Expected result
- After full completion of the chart, it must stop rather than restarting again from the beginning.

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved @suhanapradhan
