### ISSUE TITLE
Bug: Staging>>CMS>> Sever error over "News & Blogs" and "Library"

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#110]
https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/content/newsblogpage/
https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/content/librarypage/

![image](https://user-images.githubusercontent.com/25945530/108171135-2f856f00-7123-11eb-885a-ba6485002e5f.png)

**Comment by KushalRaj** [comment]
This was a temporary error. It was resolved.
