### ISSUE TITLE
Bug[UI]: Missing Searchbar (Global suppliers)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#111]
Context
- https://open-contracting.health/global-overview/data

Steps
- Data>> Global Suppliers

Actual result
- Doesn't contain a search bar.

Expected result
- Should contain a search bar.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108803066-da81a700-75c1-11eb-85ef-33f76ef70e84.png)
![image](https://user-images.githubusercontent.com/45354665/108803128-056bfb00-75c2-11eb-941d-ed64bc890a9d.png)

**Comment by nirazanbasnet** [comment]
On hold at the moment the client will provide information for this @suhanapradhan

**Comment by jpmckinney** [comment]
This is not a bug, but rather an unimplemented feature. I don't get the sense we will be implementing it, so closing.
