### ISSUE TITLE
BUG[UI]: “View in detail” button missing.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#113]
Context

- https://open-contracting.health/global-overview/data

Actual Result

- Missing "view in detail" buttons for average bids per contract and monopolization

Expected Result

- Should contain "view in detail" buttons for average bids per contract and monopolization

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108804119-83310600-75c4-11eb-8867-d35762af65f6.png)
![image](https://user-images.githubusercontent.com/45354665/108804146-8e843180-75c4-11eb-99bf-65b4d36cd397.png)

**Comment by nirazanbasnet** [comment]
On hold at the moment the client will provide information for this @suhanapradhan
