### ISSUE TITLE
BUG[UI]: Bar charts not on the same level.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#114]
Context

- https://open-contracting.health/country/mexico/data

Actual Result

- Bar graphs are not on the same level.

Expected Result

- Bar graphs should be on the same level.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108804405-487b9d80-75c5-11eb-9865-d6b88c144039.png)

**Comment by KushalRaj** [comment]
Fixed.
