### ISSUE TITLE
BUG[UI]: Missing search bar (Country suppliers)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#115]
Context

- https://open-contracting.health/country/mexico/data

Steps

- Data>> Mexico>> Country suppliers

Actual Result

- Missing search bar.

Expected result

- Searchbar must be present.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108805188-985b6400-75c7-11eb-9b32-8bb30c1b8653.png)

**Comment by jpmckinney** [comment]
Same as #111 

This is not a bug, but rather an unimplemented feature. I don't get the sense we will be implementing it, so closing.
