### ISSUE TITLE
BUGS[UI]: Posts not on the same level

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#116]
Context

- https://open-contracting.health/library

Steps

- Library>> Recent posts

Actual result

- The post isn't on the same level

Expected result

- The posts must be on the same level.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108807284-1588d800-75cc-11eb-9b53-d835f124bbdf.png)

![image](https://user-images.githubusercontent.com/45354665/108807265-099d1600-75cc-11eb-889d-effeb8373f31.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
