### ISSUE TITLE
BUGS[UI]: News display

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#117]
Context

- https://open-contracting.health/news

Steps

- Library>> News>> Featured News

Actual Result

- The display pattern on the featured news looks smaller, the title for the news isn't fully displayed.

Expected Result

- The display pattern on the featured news must be bigger. Also, display the full title of the news.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108808117-f7bc7280-75cd-11eb-8e4e-9dd74b1794f2.png)
![image](https://user-images.githubusercontent.com/45354665/108808131-060a8e80-75ce-11eb-9ec4-665630f3891f.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
