### ISSUE TITLE
BUGS[UI]: Missing search bar (news section)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#118]
Context

- https://open-contracting.health/news

Steps

- Library>> News>> Other News

Actual Result

- Missing search bar in the other news section

Expected Result

- The search bar should be present on the other news section

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108808950-ebd1b000-75cf-11eb-98f7-508968466074.png)
![image](https://user-images.githubusercontent.com/45354665/108808969-f4c28180-75cf-11eb-9a5e-31f44f5daa75.png)

**Comment by jpmckinney** [comment]
This is not a bug, but rather an unimplemented feature. I don't get the sense we will be implementing it, so closing.
