### ISSUE TITLE
BUGS[UI]: Blogs description

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#119]
Context

- https://open-contracting.health/blogs

Steps

- Library>> View all blogs>> Blogs

Actual Result

- The description of the blogs isn't displayed.

Expected Result

- A small description of the blogs must be displayed.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108809439-ef196b80-75d0-11eb-81a5-b9f274b17814.png)
![image](https://user-images.githubusercontent.com/45354665/108809452-f8a2d380-75d0-11eb-998d-704ebe1b377c.png)

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved @suhanapradhan
