### ISSUE TITLE
BUGS[UI]: Monopolization and contract status box seems to be a bit big

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#120]
Context

- https://open-contracting.health/global-overview/data

Actual Result

- The boxes for monopolization and contract status seems to be a bit big.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108810006-39e7b300-75d2-11eb-926a-1c2fc57605e4.png)
![image](https://user-images.githubusercontent.com/45354665/108810677-c5ae0f00-75d3-11eb-90c4-66913ba41f7d.png)

**Comment by nirazanbasnet** [comment]
To make equal height this kind of situation happens. So, until we add other information to this section lets leave this issue for now. @suhanapradhan
