### ISSUE TITLE
BUG[UI]: Contracts and equity indicators section missing 

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#121]
Context

- https://open-contracting.health/country/moldova/suppliers

Steps

- Data>> Contracts

Actual Result

- Doesn't match the Figma design. Contracts and equity indicators section missing.

Expected Result

- Contracts and equity indicators section to be included.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108811327-2b4ecb00-75d5-11eb-9589-1bdddc921563.png)
![image](https://user-images.githubusercontent.com/45354665/108811342-33a70600-75d5-11eb-801e-9c9827308922.png)

**Comment by nirazanbasnet** [comment]
Tested and Confirmed for Resolved @suhanapradhan
