### ISSUE TITLE
BUGS[UI]: Library>> View all news>> Featured news

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#122]
Context

- https://open-contracting.health/news/95

Steps

- Library>> View all news>> Featured news

Actual Result

- Presence of two unusual "share on" at the bottom.

Expected Result

- The "share on" at the button must be removed.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108812420-3276d880-75d7-11eb-8aba-2e537fd370ce.png)

**Comment by nirazanbasnet** [comment]
This is the content added from the CMS so issue from the frontend side @suhanapradhan
