### ISSUE TITLE
BUG[UI]: Different sizes for resource boxes

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#123]
Context

- https://open-contracting.health/library

Steps

- Library>> Resources

Actual Result

- The size of resources boxes is different.

Expected Result

- The sizes for the resources boxes should be same.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108813678-97333280-75d9-11eb-9566-e6b9306f75f6.png)

**Comment by nirazanbasnet** [comment]
This happens in the nature of the text which is dynamic so no issue so far @suhanapradhan
