### ISSUE TITLE
BUGS[UI]: Graphs on the products timeline aren't displayed 

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#125]
Context
https://open-contracting.health/suppliers/21039

Steps
Data>> Mexico>> Suppliers>> Product timeline

Actual Result
The product timeline graph isn't displayed.

Expected Result
The product timeline graph must be displayed.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108816941-34dd3080-75df-11eb-9393-d0fc934ddf5f.png)

**Comment by KushalRaj** [comment]
Fixed.
