### ISSUE TITLE
BUG[UI]: Responsiveness

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#126]
Context

- https://open-contracting.health/

Actual Result

- The 'about' section in the navbar is lost.

Expected Result

- The 'about' in the navbar should be present.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108955994-218d9c00-7697-11eb-9863-6c25aa8a76c9.png)
![image](https://user-images.githubusercontent.com/45354665/108955969-189cca80-7697-11eb-9b3d-56f0352885a5.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
