### ISSUE TITLE
BUG[UI]: Missing concentration section (country profile)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#129]
Context

- https://open-contracting.health/country/mexico/data

Actual Result

- Concentration section missing on the country profile.

Expected Result

- Concentration section present on the Figma design.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/108964686-e5ad0380-76a3-11eb-9fe5-68194c7ba463.png)
![image](https://user-images.githubusercontent.com/45354665/108964806-12f9b180-76a4-11eb-9050-639986d519c3.png)

**Comment by KushalRaj** [comment]
This visualization has now been implemented.
