### ISSUE TITLE
BUG: No any data displayed (Kyrgyzstan)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#131]
Context

- https://open-contracting.health/country/kyrgyzstan/data

Steps

- Kyrgyzstan>> Data

Actual data

- The data fields are empty

Expected data

- The data field should be displayed

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109114500-dbebd480-7765-11eb-82ec-8a0e1473d391.png)
![image](https://user-images.githubusercontent.com/45354665/109114813-413fc580-7766-11eb-9616-43f025af0034.png)
![image](https://user-images.githubusercontent.com/45354665/109114850-4f8de180-7766-11eb-9063-8f76201836bf.png)
![image](https://user-images.githubusercontent.com/45354665/109114868-561c5900-7766-11eb-811b-a7a074df87d7.png)

**Comment by KushalRaj** [comment]
Only country record was created but no country data were uploaded. Now uploaded and shown.
