### ISSUE TITLE
BUGS[UI]: Not clear information about the data differentiation

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#132]
Context

- https://open-contracting.health/global-overview/data

Steps

- Data>> Direct/Open

Actual Result

- Not clear information about the data differentiation

Expected Result

- Would be better if it contains information as open or direct

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109115560-59fcab00-7767-11eb-9054-75fa8a8da6eb.png)
![image](https://user-images.githubusercontent.com/45354665/109115590-654fd680-7767-11eb-8589-81327817fbdb.png)

**Comment by KushalRaj** [comment]
Fixed.
