### ISSUE TITLE
BUGS: Empty fields (Resource)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#133]
Context
https://open-contracting.health/resources/88

Steps
Library>> Resource

Actual Result
The topic and language fields are empty.

Expected Result
The information must be filled in the empty fields.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109120130-a8ad4380-776d-11eb-8e82-27446874e203.png)

**Comment by jpmckinney** [comment]
Language now appears. In the CMS, the Topic dropdown is empty. I believe this is too low-priority to change.
