### ISSUE TITLE
BUGS[UI]: Missing search icon (Homepage)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#134]
Context

- https://open-contracting.health/

Actual Result

- Missing search icon 

Expected Result

- Search icon present on the Figma design

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109126646-9931f880-7775-11eb-8c21-d8958954ab0a.png)
![image](https://user-images.githubusercontent.com/45354665/109125865-af8b8480-7774-11eb-877d-ef94db2a5b6c.png)

**Comment by KushalRaj** [comment]
This feature is outside of the current scope.

**Comment by jpmckinney** [comment]
Closing as out of scope.
