### ISSUE TITLE
BUGS[UI]: Responsiveness (Alignment in library section)

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#136]
Context

- https://open-contracting.health/global-overview/insights

Steps:

- Data>> Insights

Actual Result

- The alignment for the news in the library section is disturbed while responsive.

Expected Result

- Should have proper alignment while responsive.

![image](https://user-images.githubusercontent.com/45354665/109256812-e918ca00-781e-11eb-85ab-e278fe0fd785.png)
![image](https://user-images.githubusercontent.com/45354665/109254446-229b0680-781a-11eb-8dd4-7cc7a23822c6.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
