### ISSUE TITLE
BUGS[UI]: Blogs spacings different

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#137]
Context

- https://open-contracting.health/blogs

Steps

- Library>> View all blogs>> Blogs

Actual Result

- The blog spacings for all the blogs aren't the same. 

Expected Result

- The blog spacings for all blogs should be the same.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109281408-5db22f80-7844-11eb-8d67-7b2df86af662.png)
![image](https://user-images.githubusercontent.com/45354665/109281453-6b67b500-7844-11eb-84b1-92206459d4b5.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
