### ISSUE TITLE
BUGS[UI]: Race chart overlaps the date

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#138]
Context

- https://open-contracting.health/

Steps

- Homepage>> Explore countries>> Charts>> Africa/ North America

Actual Result

- The race chart for Africa and North America overlaps the date.

Expected Result

- The race chart for Africa and North America should not overlap the date.
- According to Figma design, the date is on the left side.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109464148-4c5c6380-7a8e-11eb-9735-bb0dafee7b45.png)
![image](https://user-images.githubusercontent.com/45354665/109754788-c74b8880-7c0c-11eb-8921-04b52c194ebb.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan

**Comment by suhanapradhan** [comment]
The chart still overlaps the date @nirazanbasnet
