### ISSUE TITLE
BUGS[UI]: Spacing for data in statistics 

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#139]
Context

- https://open-contracting.health/

Steps

- Homepage>> Statistics

Actual Result

- The spacing in statistics isn't the same.

Expected Result

- The spacing in statistics should be the same.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109464866-75c9bf00-7a8f-11eb-98f4-a08a6542d594.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed for resolved @suhanapradhan
