### ISSUE TITLE
BUGS[UI]: The date on the race chart

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#141]
Context

- https://open-contracting.health/global-overview/data

Actual Result

- The date is on the right side.

Expected Result

- According to Figma design, the date is on the left side below the race chart.

![image](https://user-images.githubusercontent.com/45354665/109762833-59f22480-7c19-11eb-8134-5aac3d257464.png)
![image](https://user-images.githubusercontent.com/45354665/109767562-d2f47a80-7c1f-11eb-9ccf-1844e0a0974f.png)

**Comment by KushalRaj** [comment]
This implementation as per design was not possible.
