### ISSUE TITLE
BUG: Sorting in the table isn't working

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#142]
Context

- https://open-contracting.health/global-overview/products

Steps

- Data>> Products

Actual Result

- The products aren't sorted in ascending or descending order.

Expected Result

- The products should be sorted in ascending and descending order.

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/109796110-dbf54400-7c3f-11eb-90fb-231b597b7b27.png)

**Comment by jpmckinney** [comment]
Confirmed still a bug.

**Comment by jpmckinney** [comment]
Fixed by https://github.com/open-contracting/covid-19-procurement-explorer-public/pull/342

**Comment by jpmckinney** [comment]
More general issue is https://github.com/open-contracting/covid-19-procurement-explorer/issues/100
