### ISSUE TITLE
Check overall performance of the website load time

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#144]
Check the overall performance of the website load time e.g. with this tool or any relevant other  https://gtmetrix.com/reports/www.open-contracting.health/5pStwvsz/

**Comment by jpmckinney** [comment]
For frontend, maybe useful: https://blog.logrocket.com/debugging-performance-problems-in-react/

**Comment by jpmckinney** [comment]
Performance seems to have improved enough.
