### ISSUE TITLE
Rename the title of the indicator within the country profile in Django

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#145]
Location - [Django - Country section - Countries - Country profile](URL) https://admin.open-contracting.health/admin/country/country/10/change/
Please rename the title of the "Healthcare budget" indicator to "Healthcare budget, $ per capita"
Please rename the title of the "GDP" indicator to "GDP per capita, $"

**Comment by jpmckinney** [comment]
Actually, it should be "spending" not "budget".
