### ISSUE TITLE
Fix product category in the Sunkey diagram in country profile

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#146]
Location - [Country profile - Data tab - Country Suppliers Sunkey Diagram](https://www.open-contracting.health/country/mexico/data)
For some reason, the product category skips into the supplier part of the diagram
![image](https://user-images.githubusercontent.com/18190755/113279239-8ae27980-92eb-11eb-9405-605af153c4ff.png)

**Comment by jpmckinney** [comment]
The bug highlighted by the red box above no longer appears. Assumed fixed.
