### ISSUE TITLE
Monopolization section in the data tab of the country profile is not working

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#147]
[Location Country profile - Data tab - Monopolization section](https://www.open-contracting.health/country/mexico/data)
The number displayed here & visualization does not match together. it's even more obvious on the [global profile.](https://www.open-contracting.health/global-overview/data) There's smth wrong either with the calculation or visualization.
![image](https://user-images.githubusercontent.com/18190755/113280336-cfbae000-92ec-11eb-91c6-53aa3ad5199f.png)
also, we should add at least 2 digits after the comma, it will become more meaningful this way.

**Comment by jpmckinney** [comment]
Related: https://github.com/open-contracting/covid-19-procurement-explorer-admin/issues/195

**Comment by jpmckinney** [comment]
I think one decimal is fine. For example, 2.1 and 2.2 are fine.
