### ISSUE TITLE
Filter bars at Contract tab\Buyer profile\Supplier profile lack Red flag filter

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#148]
Location: [Global profice\Country profile - Contracts tab - Filters bar above the table](https://www.open-contracting.health/global-overview/contracts) 
[buyer profile](https://open-contracting.health/buyers/14432), [supplier profile](https://open-contracting.health/suppliers/20346)

**Comment by jpmckinney** [comment]
I think we are treating this as a feature that will not be implemented.
