### ISSUE TITLE
Average bid per contract sections’ value should have digits after comma

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#151]
Location: [Both Global profile & Country profile - data tab - average bids per contract section](https://open-contracting.health/country/mexico/data) 
average bid per contract sections’ value should have at least 2 digits after the comma. same in global profile.
![image](https://user-images.githubusercontent.com/18190755/113289110-722c9080-92f8-11eb-8e84-980f20134314.png)

**Comment by jpmckinney** [comment]
I think one decimal is fine.
