### ISSUE TITLE
Add equity filter & display only equity related contract in the relevant table

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#152]
[Location Both Global Profile\ Country profile - Equity tab - filters](https://open-contracting.health/global-overview/equity)
We have to add filer by equity category

[Location Both Global Profile\ Country profile - Equity tab - table](https://open-contracting.health/global-overview/equity)
We have to display only equity-related contracts

**Comment by jpmckinney** [comment]
I think we are treating this as a feature that will not be implemented.
