### ISSUE TITLE
Add column values on the top of the product timeline bars

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#153]
Location - both [Global profile Country profile - data tab - product timeline ](https://open-contracting.health/global-overview/data)
Can we add at the top information about the total value\contract numbers at the top of the bar?

![image](https://user-images.githubusercontent.com/18190755/113296646-69d95300-9302-11eb-88b5-6c71d443ddac.png)

**Comment by jpmckinney** [comment]
I think we are treating this as a feature that will not be implemented.

A user can, at least, see the value on hover.
