### ISSUE TITLE
Fix Global suppliers section in the global profile

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#155]
Location [Global profile - data tab - global suppliers section](https://open-contracting.health/global-overview/data)
1) Delete both "Global suppliers chain" & "Global distribution chain" buttons
2) Try to leave top-3 suppliers per each product category, if it still looks messy - shrink it to the top supplier per product category.
3) Fix the question mark comment according to the previous bullet.
4) Product categories should be in the middle of the vis. just like in [[country profile]](https://open-contracting.health/country/mexico/data)
5) Small bug emerges when one clicks to the "By number" view and visualization still shows USD and $ sign 
![image](https://user-images.githubusercontent.com/18190755/113398312-1240f300-93a7-11eb-98ac-d3ad0b6c87dd.png)

**Comment by KushalRaj** [comment]
Resolved

**Comment by jpmckinney** [comment]
What is left to do in this issue?

**Comment by KushalRaj** [comment]
We have changed the view to show Top 1 supplier for each product category by tender count and amount
