### ISSUE TITLE
Hide "Contract status" section

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#158]
Location both [Global profile](https://open-contracting.health/global-overview/data) & [Country profile](https://open-contracting.health/country/kenya/data)
1) Hide "Contract status" section.
2) Do not delete the data, just hide it from the frontend.
![image](https://user-images.githubusercontent.com/18190755/113401604-4d91f080-93ac-11eb-956b-ca293396a24a.png)

**Comment by jpmckinney** [comment]
The visualization in the screenshot appears on Global and Country pages. Contract status would also be removed from the screens with individual contracts.
