### ISSUE TITLE
Add "Buyer ID" & "Supplier ID" filters

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#159]
Location both [global profile](https://open-contracting.health/global-overview/data) & [Country profile](https://open-contracting.health/country/kenya/data) - [buyers tab & suppliers tab](https://open-contracting.health/country/mexico/buyers) - filters
1) Add "Buyer ID" filter in buyers tab 
2) Add "Supplier ID " filter in suppliers tab
This should help to solve the issue with the companies that were written differently by spending units.
NB! I suppose we do not aggregate companies by company ID because of the Kenyan & similar datasets which do not include Id_s.

![image](https://user-images.githubusercontent.com/18190755/113402910-7b783480-93ae-11eb-81b0-d52837778b73.png)

**Comment by KushalRaj** [comment]
@vtarnay We have added a Buyer ID and Supplier ID column along with filters in their respective lists.
