### ISSUE TITLE
As an admin user, I want to manage covid-19 related products so that it can be used for analysis

### ISSUE THREAD

**Issue by prashantsh** [open-contracting/covid-19-procurement-explorer#16]
**Acceptance Criteria**
- The product information should include:
  - Product description
  - Product category
  - Info like what is it and why it is needed and how to use it
  - CPV code
  - icon
- Product category should also be selected
- The data about products can also be imported using excel or csv

**Comment by jpmckinney** [comment]
This has been partially (if not fully) implemented, so closing.
