### ISSUE TITLE
Fix Direct\Open section in the data tab of the global & country profiles

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#160]
Location both [Global profile & Country profile](https://open-contracting.health/global-overview/data)
1) Add "Not identified" category to the pie chart
2) Fix calculation issues 
![image](https://user-images.githubusercontent.com/18190755/113404035-38b75c00-93b0-11eb-920b-0f48b0b21d83.png)
3) Hide "view in details" tab.
![image](https://user-images.githubusercontent.com/18190755/113403838-f3932a00-93af-11eb-81d5-ae916263f22b.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed, thank you
