### ISSUE TITLE
Fix the Subscribe button 

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#164]
![image](https://user-images.githubusercontent.com/18190755/113406411-1d4e5000-93b4-11eb-9959-427a134d64b4.png)

**Comment by jpmckinney** [comment]
Not sure if related, but I'm getting browser console messages like:

> Blocked a frame with origin "https://opencontracting.substack.com" from accessing a frame with origin "https://www.open-contracting.health". Protocols, domains, and ports must match.

**Comment by jpmckinney** [comment]
Actually, I'm able to subscribe using the current box. It just doesn't give clear feedback, but that's maybe a limitation of the Substack embed widget.
