### ISSUE TITLE
Red flag "high contract value"

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#170]
[Red flag "high contract value"](https://docs.google.com/spreadsheets/d/1gVrXmAu-BAUihUtiNweXPwnb0Uvzd9lNGuKUfsf35E0/edit#gid=26583489)

We can mark contracts that exceed 1% out of each product category in a certain country as risky

**Comment by jpmckinney** [comment]
I think we are treating this as a feature that will not be implemented.
