### ISSUE TITLE
Error in the calculation of the quantity of Colombian contracts

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#173]
Location
Country profile - Colombia - total contracts tab
i noticed that in Colombia for some reason on the frontend one can see 54.7 k contracts but in reality, there are not more than 44k. 

![image](https://user-images.githubusercontent.com/18190755/116082735-6c7e5c80-a6a4-11eb-898a-3bddcbfb8677.png)

![image](https://user-images.githubusercontent.com/18190755/116082658-553f6f00-a6a4-11eb-8fa1-3a505a891fa6.png)

**Comment by KushalRaj** [comment]
Corrected and reviewed
