### ISSUE TITLE
Untranslated strings in Contract Explorer

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#177]
I have bumped into few untranslated strings.
Can you please add them to the transifex?
https://docs.google.com/document/d/16wwETBJCrY56s4uSx9nmalWfuaKVXWDDH-tJoyWlAVg/edit?usp=sharing

**Comment by jpmckinney** [comment]
Linked file is deleted, so I assume this was fixed.
