### ISSUE TITLE
Bugs in Kosovo

### ISSUE THREAD

**Issue by vtarnay** [open-contracting/covid-19-procurement-explorer#178]
Location Country profile - Kosovo - [buyers](https://www.open-contracting.health/country/kosovo/buyers) & [suppliers](https://www.open-contracting.health/country/kosovo/suppliers) tabs.

Bug №1 - buyers and suppliers tabs are not being calculated 
![image](https://user-images.githubusercontent.com/18190755/118609359-51929a00-b7c3-11eb-9edf-47a53e73a082.png)

Bug №2 - suppliers tab - quantity of contracts
we should have 150 contracts, in "buyers tab" one can see 148 contracts but in "suppliers tab" there are 297 (2*148) that possibly may be the cause of the old problem with the delete function not deleting properly.

Bug №3 - calculation of top buyers
For some reason, it sees procurements of the Ministry of Health as separate entities.
![image](https://user-images.githubusercontent.com/18190755/118610142-2197c680-b7c4-11eb-8a14-119e7124e0a5.png)
besides that, there is smth wrong with [[this line](https://www.open-contracting.health/buyers/20694)] 
![image](https://user-images.githubusercontent.com/18190755/118610794-d205ca80-b7c4-11eb-8d9e-665c8976919a.png)
it shows $956K instead of $819K
![image](https://user-images.githubusercontent.com/18190755/118610479-79363200-b7c4-11eb-8788-ae1d907a8180.png)

Bug №4 - COVID cases are not fetched for Kosovo. I have checked [our source](https://www.arcgis.com/apps/dashboards/bda7594740fd40299423467b48e9ecf6) for COVID data and they do have it but for some reason, it is not displayed on the portal.
![image](https://user-images.githubusercontent.com/18190755/118611140-31fc7100-b7c5-11eb-98b7-3b34ae2ffbb8.png)

**Comment by jpmckinney** [comment]
All seem to be fixed.
