### ISSUE TITLE
As a public user, I want to see key information related to the site on the homepage so that I can quickly go to the different parts of the site

### ISSUE THREAD

**Issue by prashantsh** [open-contracting/covid-19-procurement-explorer#21]
**Acceptance Criteria**
- In the homepage,there should be shortcut to the data page and library page
- There should be map of the different countries which have data on the platform, click on the country should display the total spending amount in USD
- There should be a section to show the featured articles from the library on the homepage

**Comment by AbhishekSka** [comment]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/admin/country/country/

### Steps ###
- Home>>Country>Edit add country
- Enter negative number on fields accepting numbers
Example: Population,GDP and so on
- Enter Special characters or Numbers for currency field

### Actual Result ###
- Negative numbers over different fields are being saved.
- Field accepts numbers and special characters

### Expected Result ###
- Fields should restrict Negative number over fields
- Special character or numbers to be restricted. Dropdown for currency could be implemented
