### ISSUE TITLE
Bug: Adding more than 10 numbers to the published date field gives NaN-NaN-NaN

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#27]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/pages/add/content/insightspage/16/?next=/cms/content/insightspage/

### Steps ###
- Overall date fields>add more than 10 numbers

### Actual Result ###
-It gives NaN-NaN-NaN

### Expected Result ###
- It should give today's date.

[Screenshots]

![image](https://user-images.githubusercontent.com/45354665/98906466-2e6df180-24e5-11eb-87f7-ecaea7934988.png)

**Comment by sonikabaniya** [comment]
Thank you @suhanapradhan , will look into it.
