### ISSUE TITLE
Bug: The documents field accepts other files like images, videos, etc

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#28]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/documents/

### Steps ###
- Documents>>Add a document>>Choose file to upload>>Update any files

### Actual Result ###
- It uploades any type of files.

### Expected Result ###
- Should accept text documents like txt, pdf, etc

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/98906319-ee0e7380-24e4-11eb-8218-6e865e4e2147.png)

**Comment by sonikabaniya** [comment]
not really sure if this is bug or not. should we limit our upload to certain mime type @prashantsh and @KushalRaj dai ?
