### ISSUE TITLE
Bug[UI]: All the body sections from different title are displayed on the insights page.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#30]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/content/eventspage/
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/33/edit/preview/

### Steps ###
- CMS>> Event list page

### Actual Result ###
 - Html tags are being displayed in listing page and on preview

### Expected Result ###
- Only a few lines can be displayed on each title making the insight page look a bit clear

[Screenshots]

![image](https://user-images.githubusercontent.com/25945530/103204008-770b2e00-491e-11eb-8802-9d2866ba16a5.png)
![image](https://user-images.githubusercontent.com/25945530/103204022-7ffbff80-491e-11eb-8140-609d79c96248.png)

**Comment by sonikabaniya** [comment]
This has been fixed previously.
