### ISSUE TITLE
An empty field is created if no author is assigned.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#31]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/content/insightspage/

### Steps ###
- Create a insight page content by leaving the content field blank 
- Insights>>By author

### Actual Result ###
- An empty field is created under **by author** field on the insights page if no author is assigned to the article.

### Expected Result ###
- There should not be any empty fields created. Only the author's name that has been added should be listed.

[Screenshots]

![image](https://user-images.githubusercontent.com/45354665/98909260-ae965600-24e9-11eb-99c7-ecf9b63266cd.png)

**Comment by KushalRaj** [comment]
@sonikabaniya

**Comment by jpmckinney** [comment]
Since this only affects the backend, and since all pages should have authors, I think this is fine to leave as-is.
