### ISSUE TITLE
BUG[UI]: Not clear about on what basis to search for the articles.

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#32]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/content/insightspage/

### Steps ###
- Insights>>Search bar

### Actual Result ###
- The search is done on the basis of the content(blog,news)

### Expected Result ###
- Instead of "search insights page" on the search placeholder, a clear vision of on what basis are we searching for articles(eg: search by content types, search by countries)

[Screenshots]

![image](https://user-images.githubusercontent.com/45354665/98910353-26b14b80-24eb-11eb-902c-97e3f8622a87.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
