### ISSUE TITLE
BUGS: Some files less than 10MB cannot be uploaded   

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#33]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/images/multiple/add/

### Steps ###
- Images>> Add images

### Actual Result ###
- Files less then 10MB aren't uploaded

### Expected Result ###
- File less than 10MB should be uploaded. 

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/98925499-2b332f80-24fe-11eb-8faf-03f55e54be89.png)
![image](https://user-images.githubusercontent.com/45354665/98926266-2fac1800-24ff-11eb-8c39-288ccf3bf8f3.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed. Supporting screenshots:

![image](https://user-images.githubusercontent.com/20502698/104563039-44c53480-5671-11eb-9b7a-4d59d47aa618.png)
<img width="428" alt="Screen Shot 2021-01-14 at 2 02 31 PM" src="https://user-images.githubusercontent.com/20502698/104563155-66beb700-5671-11eb-952b-9b2dae9e125f.png">
