### ISSUE TITLE
 Only the external link to be attached on the body field

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#34]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/cms/pages/add/content/insightspage/1/?next=/cms/content/insightspage/

### Steps ###
- Insights>>Add new insights>>Add link on body section

### Actual Result ###
- Can attach internal link as well as external link

### Expected Result ###
- Attach only external links on the body section.

[Screenshots]

![image](https://user-images.githubusercontent.com/45354665/98927552-c75e3600-2500-11eb-9a89-cf8261b2b182.png)

**Comment by sonikabaniya** [comment]
@AbhishekSka dai, help me to understand what does "Can attach internal link as well as external link" means here.

**Comment by KushalRaj** [comment]
@sonikabaniya any update on this issue?

**Comment by jpmckinney** [comment]
It sounds like an admin can accidentally add both internal and external links. I think it is fine to expect the admin to not make such accidents.
