### ISSUE TITLE
 Bug: Negative entries accepted in the numbers fields

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#35]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/admin/country/country/9/change/

### Steps ###
- Countries/Tenders>>Add Country/ Add tenders>> Negative entries in the number fields .

### Actual Result ###
- Accepting all the negative entries in number fields like population, healthcare budget, etc.
 
### Expected Result ###
- Should not accept any negative entries.

**Comment by bigyan** [comment]
The issue has been fixed.
