### ISSUE TITLE
 Bug: [No boundary for percentage]

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#36]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/admin/country/country/9/change/

### Steps ###
- Countries>> Add Country>> Percentage fields(% of GDP to healthcare, Unemployment rate, Gender distribution, % of Procurement to GDP, % from total procurement market)

### Actual Result ###
- Accepts more than 100% in percentage fields like GDP.

### Expected Result ###
- Should not accept more than 100% in percentage fields.
- The addition of gender distribution for males and females should be 100%.

**Comment by bigyan** [comment]
The issue has been fixed.
