### ISSUE TITLE
Bug: Doesn't accept more than 10 digits  entry in Population field

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#37]
### Context ###
-https://covid19admin.py.staging.yipl.com.np/admin/country/country/

### Steps ###
- Countries>> Add Country>> Population

### Actual Result ###
- More than 10 digits in the population field gives "Ensure this value is less than or equal to 2147483647." message

### Expected Result ###
- Should accept more than 10 digits 

[Screenshots]

![image](https://user-images.githubusercontent.com/45354665/99628765-ead43400-2a5e-11eb-9879-6d0f5ca6ede3.png)

**Comment by bigyan** [comment]
This issue has been fixed.
