### ISSUE TITLE
 Bug: Accepts numbers and special characters on name of country field

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#39]
### Context ###
- https://covid19admin.py.staging.yipl.com.np/admin/country/country/9/change/

### Steps ###
- Countries>> Add Country>> Name

### Actual Result ###
- Numbers and special characters are also accepted in the name of country fields.

### Expected Result ###
- Only letters should be accepted. Numbers and special characters should not be accepted in the name of country fields.

**Comment by bigyan** [comment]
The issue has been fixed.
