### ISSUE TITLE
BUGS: Same start time and end time is accepted

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#40]
Context
https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/20/edit/?next=/cms/content/eventspage/

Steps
Events>> Add Events>> Start time-2.00>> End Time-2:00
Events>> Add Events>> Start time-11:00>> End Time-2:00

Actual Result
Same start time and end time is accepted.
End time forward to start time is being accepted

Expected Result
The same start and end time should not be accepted.
End time shouldnt be forward than start time

[Screenshots]
![image](https://user-images.githubusercontent.com/45354665/101596329-fcd14300-3a1c-11eb-8fed-c72b481c3fec.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
