### ISSUE TITLE
BUGS[UI]: Country Page[Buyers]

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#43]
Context:
https://covid19.development.opencontracting.uk0.bigv.io/country/mexico

Screenshots:

- Buyer box smaller than the other two
![image](https://user-images.githubusercontent.com/45354665/101876367-66d02080-3bb4-11eb-8561-eb817562344e.png)

**Comment by nirazanbasnet** [comment]
Fixed
