### ISSUE TITLE
BUG[UI]: Country Page[Equity]

### ISSUE THREAD

**Issue by suhanapradhan** [open-contracting/covid-19-procurement-explorer#44]
Context:
https://covid19.development.opencontracting.uk0.bigv.io/country/mexico

Screenshots:
![image](https://user-images.githubusercontent.com/45354665/101880742-83bc2200-3bbb-11eb-84d9-d2b197f20d9f.png)
![image](https://user-images.githubusercontent.com/45354665/101880882-b6feb100-3bbb-11eb-8dfb-3329660487a7.png)

**Comment by nirazanbasnet** [comment]
This section is currently removed
