### ISSUE TITLE
Bug: Date format on News thumbnail should be of Dec 23,2020

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#45]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/

### Steps ###
- Home>>News thumbnail 

### Actual Result ###
- shows date with in the format 202012-02

### Expected Result ###
- Dates are to be dispalye in format Dec 15,2020 inorder to maintain consistency all over the system
- 
[Screenshots]
![image](https://user-images.githubusercontent.com/25945530/102970932-848c7680-4520-11eb-833d-39d10bf86554.png)
expected
![image](https://user-images.githubusercontent.com/25945530/102970990-a4bc3580-4520-11eb-9207-4ba250054f00.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
