### ISSUE TITLE
Bug: Event details gives error on console

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#49]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/events-detail/18

### Steps ###
- Open detail page for events

### Actual Result ###
-  Error on the console

### Expected Result ###
- Event page with event details should be seen

![image](https://user-images.githubusercontent.com/25945530/103076663-5a0ced00-45f6-11eb-9d25-e63c2b2879f3.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
