### ISSUE TITLE
Bug: CMS>>Tag>> Unable to create new tag if the word is already in it

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#50]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/add/content/insightspage/17/#upload

### Steps ###
- Edit the insight content
- On tag >> add the tag "Travel quarantine"
- Try to add "Travel" for tag

### Actual Result ###
-  Unable to add "Travel" for tag
 
### Expected Result ###
- User should be allowed to add "Travel" even "Travel quarantine" has already been added

![image](https://user-images.githubusercontent.com/25945530/103077434-da801d80-45f7-11eb-8710-78662959f9ef.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed with supporting screenshot :

<img width="1413" alt="Screen Shot 2021-01-14 at 12 12 06 PM" src="https://user-images.githubusercontent.com/20502698/104553081-1e4bcd00-5662-11eb-8f4a-c69140cbbae6.png">
