### ISSUE TITLE
Bug: CMS>Insights without Content image shown with broken image on news details and broken thumbnail on library page

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#51]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/22/edit/
- https://covid19.development.opencontracting.uk0.bigv.io/news-detail/22
- https://covid19.development.opencontracting.uk0.bigv.io/news

### Steps ###
- CMS >> Create Insight without the Content Image
-  And publish
- Check for it on Staging site

### Actual Result ###
- Broken thumbnail on news page
- Broken image on news detail 

### Expected Result ###
- Default thumbnail image is to to be set if no content image is present
- Image is to be ignored in the news detail if not enter

![image](https://user-images.githubusercontent.com/25945530/103080754-a2c8a400-45fe-11eb-9938-4e7e4c4c6bbd.png)
![image](https://user-images.githubusercontent.com/25945530/103080912-f6d38880-45fe-11eb-890a-4d6f49c89a2d.png)

**Comment by nirazanbasnet** [comment]
Done
