### ISSUE TITLE
Bug : Bug: Library/News/Blog/events page>> Caption placed under the thumbnail should be at most of two lines

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#52]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/news

### Steps ###
- Add longest title for blog/news/event

### Actual Result ###
- Check for the caption below for thumbnail which goes from more than two lines

### Expected Result ###
- Caption should be atmost of two lines

![image](https://user-images.githubusercontent.com/25945530/103085996-6d768300-460b-11eb-9e74-edaa52ab4c9d.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
