### ISSUE TITLE
Bug: CMS>>Pictures/Video/ Numbered/File bullet on the Body of insight are not available on site

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#53]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/22/edit/
- https://covid19.development.opencontracting.uk0.bigv.io/news-detail/22
- https://covid19.development.opencontracting.uk0.bigv.io/news

### Steps ###
- CMS >> Create Insight with image,file or video content in Body field
-  And publish
- Check for it on Staging site

### Actual Result ###
- No Video or image could be seen 

### Expected Result ###
- Image and video are to be display as per set up on the body of insight

![Screenshot from 2020-12-24 16-11-54](https://user-images.githubusercontent.com/25945530/103082680-c5f55280-4602-11eb-9ac8-8a66cac26667.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
