### ISSUE TITLE
Bug: CMS>>News & Blog listing page>> Tags are named as content.InsightsPage.None

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#56]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/content/insightspage/

### Steps ###
- CMS >> News & Blogs
-  Under "Tags" Column
- Check for Tag 

### Actual Result ###
- Tags are displayed as content.InsightsPage.None
- 
### Expected Result ###
- Assigned/Created tags are to be shown

![image](https://user-images.githubusercontent.com/25945530/103190905-f850c980-48fa-11eb-97e3-4a25524dc2e8.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
