### ISSUE TITLE
Bug: Missing fields detail on the events details post

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#58]
### Context ###
- https://admin.covid19.development.opencontracting.uk0.bigv.io/cms/pages/33/edit/?next=/cms/content/eventspage/
- https://covid19.development.opencontracting.uk0.bigv.io/events-detail/33

### Steps ###
- CMS >> create Event with all the fileds filled
- Publish the event 
- Check for the event details on the site
 
### Actual Result ###
- Details over Date,organisation and location is missing for the event

### Expected Result ###
- Date,organisation and location should be shown as per design

![image](https://user-images.githubusercontent.com/25945530/103202222-ecc0cb00-4919-11eb-9b36-79430ec55e7d.png)
![image](https://user-images.githubusercontent.com/25945530/103202241-fb0ee700-4919-11eb-9e4d-615d14cef77d.png)

**Comment by nirazanbasnet** [comment]
Done
