### ISSUE TITLE
Bug: Unable to access blog detail page 

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#59]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/blogs-detail/15

### Steps ###
- Library>>blog

### Actual Result ###
- error on console
- 
### Expected Result ###
- Blog post should be displayed as per  published data over cms
 
![image](https://user-images.githubusercontent.com/25945530/103257898-2f86af80-49bb-11eb-85af-03585142a51d.png)

**Comment by sonikabaniya** [comment]
This issue has been fixed
