### ISSUE TITLE
 Bug: Homepage>> Bar doesnt have metrics on the map

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#61]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/

### Steps ###
- Home page>>explore countries

### Actual Result ###
- Data bar doesn't have any data and is not working 

### Expected Result ###
- Bar should be implemented as per design

![image](https://user-images.githubusercontent.com/25945530/103258532-7d9cb280-49bd-11eb-863e-3ca72ef779d6.png)
 
![image](https://user-images.githubusercontent.com/25945530/103258543-8ab9a180-49bd-11eb-9cf8-24fba193bc0f.png)

**Comment by nirazanbasnet** [comment]
Fixed
