### ISSUE TITLE
Bug: Global overview>> On viewing graphs such as PRODUCTS TIMELINE/GLOBAL SUPPLIERS shows the graph for COVID/CONTRACTS QUANTITY CORRELATION

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#62]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/data
 

### Steps ###
- View full screen for Graphs
- PRODUCTS TIMELINE/GLOBAL SUPPLIERS

### Actual Result ###
- On viewing full screen, Graph is being redirected to  COVID/CONTRACTS QUANTITY CORRELATION

### Expected Result ###
-  Respective graph should be shown

![image](https://user-images.githubusercontent.com/25945530/103265310-69fd4600-49d5-11eb-85a7-44d6156bf6e9.png)

**Comment by nirazanbasnet** [comment]
Done
