### ISSUE TITLE
Bug: Sanky chart >>Graph on hold and drag would produce minimize icon

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#63]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/data
- https://covid19.development.opencontracting.uk0.bigv.io/country/ukraine
 

### Steps ###
- graphs for TOTAL SPENDING,TOTAL CONTRACT,AVERAGE BID FOR CONTRACT ,MONOPOLIZATION
- hold and drag

### Actual Result ###
- Minimize button could be seen
- 
### Expected Result ###
- Removed minimize button as it doesnt have any purpose

![image](https://user-images.githubusercontent.com/25945530/103338699-57534180-4aa7-11eb-96df-d34abe6b84ba.png)

**Comment by duptitung** [comment]
@AbhishekSka It is used to go back to reset the zoom as dragging will add zoom in the graph. It is a necessary as there is no other way to zoom out.

**Comment by AbhishekSka** [comment]
solved
