### ISSUE TITLE
Improve the popup value display

### ISSUE THREAD

**Issue by prashantsh** [open-contracting/covid-19-procurement-explorer#64]
The popup value display on the world map needs to have the currency infront and also trimmed to show in K, M or B.

<img width="1365" alt="Screen Shot 2021-01-18 at 10 21 56" src="https://user-images.githubusercontent.com/3199381/104872875-2dd75880-5977-11eb-8bad-2b3d2e46ac3a.png">

**Comment by nirazanbasnet** [comment]
Done
