### ISSUE TITLE
Bug: Any Country>>COUNTRY PARTNER ORGANIZATION >>Slider is not implemented as per design

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#75]
### Actual Result ####

![image](https://user-images.githubusercontent.com/25945530/105013236-23948780-5a67-11eb-841c-a67b6889a9e7.png)

### Expected result ####

![image](https://user-images.githubusercontent.com/25945530/105013306-37d88480-5a67-11eb-8c04-328244bbdea8.png)

**Comment by nirazanbasnet** [comment]
Done
