### ISSUE TITLE
Bug>> Supplier Tab >> Unavailable bar chart for Supplier's >>"TOTAL SPENDING"

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#76]
https://covid19.development.opencontracting.uk0.bigv.io/global-overview/buyers

![image](https://user-images.githubusercontent.com/25945530/105032145-81809980-5a7e-11eb-8b7c-66dc944e9fab.png)

**Comment by nirazanbasnet** [comment]
Fixed
