### ISSUE TITLE
Bug: Contents on "Contract Status" visualization is compressed with space left on lower part

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#78]
![image](https://user-images.githubusercontent.com/25945530/105136485-d2919b80-5b19-11eb-9542-da8a7fccc7c2.png)

**Comment by KushalRaj** [comment]
@nirazanbasnet  we utilize this space by space by increasing space between those status items

**Comment by nirazanbasnet** [comment]
Done
