### ISSUE TITLE
Bug: Show "By contract value"/"By number of contracts" beside the title on as per design

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#80]
- [x] TOP SUPPLIER
### Actual result ###
![image](https://user-images.githubusercontent.com/25945530/105139085-eb03b500-5b1d-11eb-9f01-90b8fc44729c.png)

### Expected result ###
![image](https://user-images.githubusercontent.com/25945530/105139108-f2c35980-5b1d-11eb-8917-08d98d066f07.png)

- [x] TOP BUYER
### Actual result ###
![image](https://user-images.githubusercontent.com/25945530/105139138-feaf1b80-5b1d-11eb-934b-dbcc8ba88e6e.png)

### Expected result ###
![image](https://user-images.githubusercontent.com/25945530/105139163-08388380-5b1e-11eb-9cff-af96c30714ec.png)

- [x]  PRODUCT DISTRIBUTION
### Actual result ###
![image](https://user-images.githubusercontent.com/25945530/105139220-1dadad80-5b1e-11eb-8967-32c7a84c48bc.png)

### Expected result ###
![image](https://user-images.githubusercontent.com/25945530/105139182-11c1eb80-5b1e-11eb-9a3a-e39a653e5727.png)

- [x] COVID/CONTRACTS QUANTITY CORRELATION
### Actual result ###
![image](https://user-images.githubusercontent.com/25945530/105139259-2ef6ba00-5b1e-11eb-92c7-15f1077197b7.png)

### Expected result ###
![image](https://user-images.githubusercontent.com/25945530/105139278-34ec9b00-5b1e-11eb-98b5-16a203a1e345.png)

- [x] COUNTRY SUPPLIER
### Actual result ###
![image](https://user-images.githubusercontent.com/25945530/105139610-97de3200-5b1e-11eb-9e5e-06f1009b66de.png)

### Expected result ###
![image](https://user-images.githubusercontent.com/25945530/105139802-e2f84500-5b1e-11eb-8961-7bccd3cb6233.png)

**Comment by KushalRaj** [comment]
@nirazanbasnet 
Also `$` sign is missing in amounts when we are viewing by contract value. By default it will show $ as we are showing amount in USD. It should change accordingly when we switch to Local currency

**Comment by nirazanbasnet** [comment]
Done
