### ISSUE TITLE
Bug: Unable to view the value for lowest value on bar graph 

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#81]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/global-overview/data
 
### Steps ###
- Global>>Top spending >>Bar graph>>Hover on "Selective" 

### Actual Result ###
- Unable to see value for the lowest in bar graph 

### Expected Result ###
- Value should be shown for the bar

![Screenshot from 2021-01-20 13-12-19](https://user-images.githubusercontent.com/25945530/105141393-2b186700-5b21-11eb-9621-0df5bbff1843.png)

**Comment by nirazanbasnet** [comment]
done
