### ISSUE TITLE
Bug: Contract status api with params for country

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#82]
### Context ###
- {{api_base_url}}/api/v1/visualization/contract-status/?country=MX
 
### Steps ###
- {
        "amount_local": 3757784851.762,
        "amount_usd": 159788193.62,
        "tender_count": 2538,
        "local_currency_code": "",
        "status": "active"
    }

### Actual Result ###
-  "local_currency_code": "" is blank

### Expected Result ###
-  Local currency code should be shown as per query params

![image](https://user-images.githubusercontent.com/25945530/105144168-ed1d4200-5b24-11eb-8d19-f93c282337c6.png)

**Comment by KushalRaj** [comment]
@suyojman

**Comment by KushalRaj** [comment]
Resolved in upcoming branch.
