### ISSUE TITLE
Bug: Switching in the countries in Global Page doesnt change Total Contracts visualization

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#85]
### Context ###
- https://covid19.development.opencontracting.uk0.bigv.io/country/ukraine/data
 
### Steps ###
- Global page >> United kingdom
- Check for Total contract graph/Top supplier/Top buyer/COVID/CONTRACTS QUANTITY CORRELATION 
- Switch to Ukraine

### Actual Result ###
- Graph and detials changes to Ukraine but switch back to United kingdom
-  Api for call UA and GB both are called

### Expected Result ###
- On switching country Graph and values for particular country is to be displayed
- Api for Specific country  is to be called rather than calling both

https://user-images.githubusercontent.com/25945530/105171703-a80a0780-5b46-11eb-9bf5-ca0d7ffcf858.mp4

![image](https://user-images.githubusercontent.com/25945530/105172366-9ffe9780-5b47-11eb-862a-1d4325a7a69f.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed as Resolved
