### ISSUE TITLE
Bug: Data validations over visualizatoin

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#86]
### NO. OF BUYER
**Context**
- https://open-contracting.health/global-overview/buyers
**Step**
- Global overview>>>Buyers Tab>>Buyer visualization
**Actual Result**
- Buyer count is 11525
**Expected Result**
- As per API Buyer count should be 11,609

### NO OF SUPPLIERS
**Context**
- https://covid19.development.opencontracting.uk0.bigv.io/global-overview/suppliers
**Step**
- Global overview>>>Suppliers Tab>> Suppliers visualization
**Actual Result**
- Supplier count is 15102
**Expected Result**
- As per API Supplier count should be 15254

### **ROUNDED UP "BY NUMBER" CONTRACT STATUS**
**Context**
- https://open-contracting.health/global-overview/data
**Step**
- Global/Ukraine/UK>>>Contract status >> By numbers>>Check for any of three say Active
**Actual Result**
- Active status is show as 44.5k for global
- Active status is show as 38.2k for Ukraine
- Active status is show as 2.2k for UK
**Expected Result**
- Actual count is 44471 for global
- Actual count is 38172 for ukraine
- Actual count is 2171 for uk

### **ROUNDED UP NUMBER COUNT IN SUPPLIERS**
**Context**
- https://covid19.development.opencontracting.uk0.bigv.io/global-overview/suppliers
**Step**
- Mexico>>>Suppliers Tab>> Suppliers visualization
**Actual Result**
- Supplier count is 1.3K
**Expected Result**
- Actual count is 1267

### **ROUNDED UP NUMBER TOTAL CONTRACTS**
**Context**
- https://open-contracting.health/country/united-kingdom/data
**Step**
- UK>>Top Contract visualization
**Actual Result**
- Total count is 2.2K
**Expected Result**
- Actual count is 2172

**Comment by KushalRaj** [comment]
Resolved
