### ISSUE TITLE
Bug: Global overview>>Equity indicator>> No tender count could be seen for "assigned " 

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#88]
**Context**
- https://open-contracting.health/global-overview/data

**Step**
- Global overview>>Equity indicator>>By number

**Actual Result**
- Only data for unassigned is visible

**Expected Result**
- No data could be seen for "assigned" data

![image](https://user-images.githubusercontent.com/25945530/105817904-5649fd00-5fde-11eb-9dcb-2a0eff4ace63.png)

**Comment by nirazanbasnet** [comment]
Done
