### ISSUE TITLE
Bug: Home page>>Countries map and chart issues

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#94]
- [x]  The Date has been lost
![image](https://user-images.githubusercontent.com/25945530/105954668-2281dc80-609d-11eb-936d-1a8a3036dff9.png)

- [x]  Charts-front-end 
Instead of just the year – we should see the date and the year.
Play button can not be stopped at the moment which is not right.
![image](https://user-images.githubusercontent.com/25945530/105954853-6ffe4980-609d-11eb-9679-e3c252230a39.png)

- [x] Front-end - typo: small typo on the front end “All Continents” instead of “All continent”
![image](https://user-images.githubusercontent.com/25945530/105954995-acca4080-609d-11eb-9c7e-4a8a2fb63679.png)

- [x]  Front end - lots of zeros should be changed to “M” - millions  “B” - billions  & “T” - trillions
![image](https://user-images.githubusercontent.com/25945530/105955012-b358b800-609d-11eb-8771-d51ad9dbe0dc.png)

- [x] Chart doesnt increase for Global 
![image](https://user-images.githubusercontent.com/25945530/105955168-f74bbd00-609d-11eb-84e7-deceae34dd52.png)

- [x] Play and stop button not working on charts after once played

- [x]  back-end - We need a place to be able to modify this text
![image](https://user-images.githubusercontent.com/25945530/105955260-19ddd600-609e-11eb-8d0a-2962737e2e64.png)

#19 Front-end - download & share buttons do not work
![image](https://user-images.githubusercontent.com/25945530/105955303-2d893c80-609e-11eb-9b99-b0977449e9be.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed as Resolved
