### ISSUE TITLE
Bug: Global/countries >>Insight tab issues 

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#95]
- [x] Filters to be implemented along with 1) year column; 2) tag column; 3) year filter; 4) tag filter

![image](https://user-images.githubusercontent.com/25945530/105957133-dfc20380-60a0-11eb-9659-b483d2a02586.png)

![image](https://user-images.githubusercontent.com/25945530/105957388-4c3d0280-60a1-11eb-9db3-e69b3e280713.png)

- [x]  front-end - global profile - insights tab - pictures should be of one size and text should be aligned

![image](https://user-images.githubusercontent.com/25945530/105957278-244d9f00-60a1-11eb-989d-c8a154f697ce.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed as Resolved
