### ISSUE TITLE
Bug: Buyer/Supplier tab graph issues

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#97]
- [x]  front end - global profile - buyers & suppliers tab - 1000 should be seen as K, 1 000 000 - as B, and 1000 000 000 as T.
![image](https://user-images.githubusercontent.com/25945530/105958057-37ad3a00-60a2-11eb-83f6-1e461cdec4de.png)

- [ ]  front end - global profile - buyers & suppliers  tab - smth. is wrong with the formula
![image](https://user-images.githubusercontent.com/25945530/105958098-44ca2900-60a2-11eb-9363-8799fc5770c8.png)

- [ ]  frontend - global profile - buyers & suppliers tab - download button is missing
![image](https://user-images.githubusercontent.com/25945530/105958115-4b58a080-60a2-11eb-988a-e6883ab29c06.png)

**Comment by nirazanbasnet** [comment]
Tested and Confirmed as Resolved
