### ISSUE TITLE
Bug: Buyer/Supplier detail garph unavailable

### ISSUE THREAD

**Issue by AbhishekSka** [open-contracting/covid-19-procurement-explorer#98]
- [ ] frontend - global profile - buyer & supplier tab - supplier profile crushed when one tries to click on it from the global profile both from buyer & supplier tabs.
![image](https://user-images.githubusercontent.com/25945530/105959916-a2f80b80-60a4-11eb-97bf-dafb412638db.png)

**Comment by nirazanbasnet** [comment]
Tested and confirmed as Resolved
